# docker-compose.yml
version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: postgresDB
    environment:
      POSTGRES_USER: dgauto
      POSTGRES_PASSWORD: v06n06c09
      POSTGRES_DB: gonvarDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: diego@gonvar.io
      PGADMIN_DEFAULT_PASSWORD: v06n06c09
    ports:
      - '5050:80'
    networks:
      - postgres-network

volumes:
  postgres_data:

networks:
  postgres-network:
